//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace URideApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DriverInfo()
        {
            this.CarInfoes = new HashSet<CarInfo>();
        }
    
        public int DriverId { get; set; }
        public string DriverName { get; set; }
        public Nullable<System.DateTime> DriverHireDate { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Gender { get; set; }
        public string HomeAddress { get; set; }
        public string Email { get; set; }
        public string PhoneNo { get; set; }
        public string LicenseNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarInfo> CarInfoes { get; set; }
    }
}
