//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace URideApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PassengerInfo
    {
        public int PassengerId { get; set; }
        public string PassengerName { get; set; }
        public string Gender { get; set; }
        public string CellNo { get; set; }
        public string PermenantAddress { get; set; }
    }
}
